using IntervalArithmetic

include(joinpath(@__DIR__, "triangulation.jl"))
include(joinpath(@__DIR__, "inverse_metric_bounds.jl"))

"""Return the signed double area of a triangle with interval coordinates."""
function triangle_double_area(nodes, tri)
    x1, y1 = nodes[tri[1], 1], nodes[tri[1], 2]
    x2, y2 = nodes[tri[2], 1], nodes[tri[2], 2]
    x3, y3 = nodes[tri[3], 1], nodes[tri[3], 2]
    return (x2 - x1) * (y3 - y1) - (x3 - x1) * (y2 - y1)
end

"""Return the three constant Crouzeix--Raviart basis gradients."""
function cr_gradients(nodes, tri)
    x1, y1 = nodes[tri[1], 1], nodes[tri[1], 2]
    x2, y2 = nodes[tri[2], 1], nodes[tri[2], 2]
    x3, y3 = nodes[tri[3], 1], nodes[tri[3], 2]
    determinant = triangle_double_area(nodes, tri)
    inf(determinant) > 0 || error("Triangle $tri is not positively oriented")
    return -interval(BigFloat(2)) * [
        y2 - y3  x3 - x2
        y3 - y1  x1 - x3
        y1 - y2  x2 - x1
    ] / determinant
end

"""Return the local diagonal Crouzeix--Raviart mass matrix."""
function local_cr_mass_matrix(nodes, tri)
    area = triangle_double_area(nodes, tri) / interval(BigFloat(2))
    inf(area) > 0 || error("Triangle $tri has nonpositive area")
    mass = fill(zero(area), 3, 3)
    for index in 1:3
        mass[index, index] = area / interval(BigFloat(3))
    end
    return mass
end

"""Return the local stiffness matrix for a constant point coefficient `B`."""
function local_cr_stiffness_matrix(nodes, tri, B)
    size(B) == (2, 2) || throw(ArgumentError("B must be a 2-by-2 matrix"))
    area = triangle_double_area(nodes, tri) / interval(BigFloat(2))
    gradients = cr_gradients(nodes, tri)
    coefficient = point_interval_matrix(B)
    stiffness = fill(zero(area * coefficient[1, 1]), 3, 3)
    for a in 1:3, b in 1:3
        stiffness[a, b] = area * (
            gradients[a, 1] * coefficient[1, 1] * gradients[b, 1] +
            gradients[a, 1] * coefficient[1, 2] * gradients[b, 2] +
            gradients[a, 2] * coefficient[2, 1] * gradients[b, 1] +
            gradients[a, 2] * coefficient[2, 2] * gradients[b, 2]
        )
    end
    return stiffness
end

"""Return the three opposite edges used as local CR degrees of freedom."""
local_cr_edges(tri) = ((tri[2], tri[3]), (tri[3], tri[1]), (tri[1], tri[2]))

"""Return a canonical ordered key for an undirected edge."""
edge_key(i, j) = minmax(i, j)

"""Insert an edge into the global CR numbering and return its index."""
function edge_index!(edge_ids, edges, edge)
    key = edge_key(edge...)
    haskey(edge_ids, key) && return edge_ids[key]
    push!(edges, key)
    edge_ids[key] = length(edges)
    return length(edges)
end

"""Build the global edge degrees of freedom for a triangle list."""
function build_cr_edges(triangles)
    edge_ids = Dict{Tuple{Int,Int},Int}()
    edges = Tuple{Int,Int}[]
    triangle_edge_ids = Tuple{Int,Int,Int}[]
    for tri in triangles
        local_edges = local_cr_edges(tri)
        ids = ntuple(index -> edge_index!(edge_ids, edges, local_edges[index]), 3)
        push!(triangle_edge_ids, ids)
    end
    return edges, triangle_edge_ids
end

"""Add one dense local interval block to a sparse dictionary matrix."""
function add_block!(matrix, dofs, block)
    for a in 1:3, b in 1:3
        value = block[a, b]
        isequal_interval(value, zero(value)) && continue
        key = (dofs[a], dofs[b])
        matrix[key] = get(matrix, key, zero(value)) + value
    end
    return matrix
end

"""Rotate an integer lattice key by `steps` sixth-turns."""
function rotate_key(key, steps::Integer)
    steps >= 0 || throw(ArgumentError("steps must be nonnegative"))
    for _ in 1:steps
        key = (-key[2], key[1] + key[2])
    end
    return key
end

"""Reflect a sector lattice key across the lower-square diagonal."""
sector_reflect_key((a, b)) = (a, -a - b)

"""Return exact doubled midpoint lattice keys for CR edge degrees of freedom."""
function edge_midpoint_keys(edges, node_keys)
    return [
        (node_keys[i][1] + node_keys[j][1], node_keys[i][2] + node_keys[j][2])
        for (i, j) in edges
    ]
end

"""Find a root in a disjoint-set forest and compress its path."""
function find_root!(parent, index)
    while parent[index] != index
        parent[index] = parent[parent[index]]
        index = parent[index]
    end
    return index
end

"""Return consecutive quotient indices generated by the declared pairs."""
function quotient_map(count::Integer, pairs)
    parent = collect(1:count)
    for (left, right) in pairs
        left_root = find_root!(parent, left)
        right_root = find_root!(parent, right)
        left_root == right_root || (parent[right_root] = left_root)
    end
    root_ids = Dict{Int,Int}()
    return [
        get!(root_ids, find_root!(parent, index), length(root_ids) + 1)
        for index in 1:count
    ]
end

"""Return the D6-invariant quotient map for sector CR edge unknowns."""
function d6_edge_quotient(edges, node_keys)
    midpoints = edge_midpoint_keys(edges, node_keys)
    edge_ids = Dict(midpoints[index] => index for index in eachindex(midpoints))
    pairs = Tuple{Int,Int}[]
    for index in eachindex(midpoints)
        reflected = sector_reflect_key(midpoints[index])
        haskey(edge_ids, reflected) && push!(pairs, (index, edge_ids[reflected]))
        if midpoints[index][2] == -midpoints[index][1]
            rotated = rotate_key(midpoints[index], 1)
            haskey(edge_ids, rotated) && push!(pairs, (index, edge_ids[rotated]))
        end
    end
    return quotient_map(length(edges), pairs)
end

"""Return a rigorous upper bound for the longest side of a triangle."""
function triangle_diameter_upper(nodes, tri)
    diameter = BigFloat(0)
    for (a, b) in ((1, 2), (2, 3), (3, 1))
        dx = nodes[tri[a], 1] - nodes[tri[b], 1]
        dy = nodes[tri[a], 2] - nodes[tri[b], 2]
        diameter = max(diameter, sup(sqrt(dx^2 + dy^2)))
    end
    isfinite(diameter) && diameter > 0 || error("Triangle $tri has invalid diameter")
    return diameter
end

"""Return the rigorous local Liu constant `0.1893 h_T/sqrt(alpha_T)`."""
function local_liu_constant(diameter_upper, alpha_lower)
    alpha_lower > 0 || error("The ellipticity lower bound must be positive")
    factor = interval(BigFloat(1893)) / interval(BigFloat(10000))
    value = factor * interval(diameter_upper) / sqrt(interval(alpha_lower))
    upper = sup(value)
    isfinite(upper) && upper > 0 || error("The local Liu constant is invalid")
    return upper
end

"""Certify one element, increasing the forced box depth until quality holds."""
function certify_element(oracle, mesh, tri, degree, terms, bisection_steps, quality_threshold)
    diameter = triangle_diameter_upper(mesh.nodes, tri)
    forced_depth = 0
    while true
        bound = inverse_metric_lower_bound(
            oracle,
            mesh.nodes,
            tri,
            forced_depth,
            degree,
            terms,
            bisection_steps,
        )
        liu_constant = local_liu_constant(diameter, bound.alpha)
        liu_constant <= quality_threshold &&
            return (; B = bound.B, alpha = bound.alpha, liu_constant, forced_depth)
        forced_depth += 1
    end
end

"""Construct the certified comparison matrix on every mesh element."""
function certify_elements(
    oracle,
    mesh,
    degree,
    terms,
    bisection_steps,
    quality_target,
    progress_interval,
)
    progress_interval > 0 || throw(ArgumentError("progress_interval must be positive"))
    target = inf(interval(BigFloat(numerator(quality_target))) /
                 interval(BigFloat(denominator(quality_target))))
    certificates = Vector{Any}(undef, length(mesh.triangles))
    for index in eachindex(mesh.triangles)
        certificates[index] = certify_element(
            oracle,
            mesh,
            mesh.triangles[index],
            degree,
            terms,
            bisection_steps,
            target,
        )
        if index % progress_interval == 0 || index == length(mesh.triangles)
            println("certified $index / $(length(mesh.triangles)) elements")
            flush(stdout)
        end
    end
    return certificates
end

"""Assemble the D6-quotient CR mass and certified comparison stiffness matrices."""
function assemble_matrices(mesh, certificates)
    length(certificates) == length(mesh.triangles) ||
        throw(DimensionMismatch("Expected one certificate per triangle"))
    edges, triangle_edge_ids = build_cr_edges(mesh.triangles)
    quotient = d6_edge_quotient(edges, mesh.node_keys)
    mass = Dict{Tuple{Int,Int},Interval{BigFloat}}()
    stiffness = Dict{Tuple{Int,Int},Interval{BigFloat}}()
    for index in eachindex(mesh.triangles)
        tri = mesh.triangles[index]
        dofs = ntuple(position -> quotient[triangle_edge_ids[index][position]], 3)
        add_block!(mass, dofs, local_cr_mass_matrix(mesh.nodes, tri))
        local_stiffness = local_cr_stiffness_matrix(
            mesh.nodes,
            tri,
            certificates[index].B,
        )
        add_block!(stiffness, dofs, local_stiffness)
    end
    liu_constant = maximum(certificate.liu_constant for certificate in certificates)
    return (; matrix_size = maximum(quotient), mass, stiffness, liu_constant)
end

"""Apply Liu's monotone FEM-to-smooth comparison to a verified endpoint."""
function liu_lower_bound(lambda_fem_lower, liu_constant_upper)
    lambda = interval(BigFloat(lambda_fem_lower))
    constant = interval(BigFloat(liu_constant_upper))
    denominator = interval(BigFloat(1)) + constant^2 * lambda
    inf(denominator) > 0 || error("Liu's comparison denominator is not positive")
    return inf(lambda / denominator)
end

"""Write named numeric arrays in the MATLAB version-4 binary format."""
function write_mat4(path, entries)
    open(path, "w") do io
        for (name, value) in entries
            array = if value isa Number
                reshape([Float64(value)], 1, 1)
            else
                reshape(Float64.(value), :, 1)
            end
            write(io, Int32(0), Int32(size(array, 1)), Int32(size(array, 2)))
            write(io, Int32(0), Int32(length(name) + 1))
            write(io, codeunits(name))
            write(io, UInt8(0))
            write(io, vec(array))
        end
    end
end

"""Widen paired interval entries so a dictionary matrix is exactly symmetric."""
function symmetrize_entries(matrix)
    symmetric = copy(matrix)
    for (i, j) in collect(keys(matrix))
        haskey(matrix, (j, i)) || continue
        value = hull(symmetric[(i, j)], symmetric[(j, i)])
        symmetric[(i, j)] = value
        symmetric[(j, i)] = value
    end
    return symmetric
end

"""Save a sparse interval matrix as outward-rounded MATLAB endpoint arrays."""
function save_interval_matrix(path, matrix, size_)
    entries = sort!(collect(keys(matrix)))
    write_mat4(path, [
        "n" => size_,
        "i" => first.(entries),
        "j" => last.(entries),
        "lo" => [Float64(inf(matrix[key]), RoundDown) for key in entries],
        "hi" => [Float64(sup(matrix[key]), RoundUp) for key in entries],
    ])
end

"""Write the fixed stiffness and mass inputs consumed by MATLAB and INTLAB."""
function write_matlab_matrices(assembly, directory)
    stiffness = symmetrize_entries(assembly.stiffness)
    mass = symmetrize_entries(assembly.mass)
    save_interval_matrix(
        joinpath(directory, "stiff_matrix.mat"),
        stiffness,
        assembly.matrix_size,
    )
    save_interval_matrix(
        joinpath(directory, "mass_matrix.mat"),
        mass,
        assembly.matrix_size,
    )
end
